### ISSUE TITLE
Job fails with errorMessage: TAPIS_SSH_NO_SESSION No SSH session exists on this connection.

### ISSUE THREAD

**Issue by chandra-tacc** [tapis-project/tapis-jobs#41] opened 2023-06-28 21:45 UTC
Details:
1) Create an application (example opensees), which takes an inputdir. 
2) For the job, provide a lot of files. In this case it has 79 files.
3) Execute the job.

Result:
errorMessage: TAPIS_SSH_NO_SESSION No SSH session exists on this connection.

More Info:
* The job uses input from file system. When the job runs, the data is transferred from input source to job execution folder, I see those files. But, then staging inputs task failed:
```A request to stage job input files has been submitted. Files service staging transaction 1271c2d0-d892-4d0e-8918-1bc57b863cd5 in state FAILED for job c3cfcc95-d808-4411-8902-c523b8172b7c-007 in tenant portals." ```
* I checked the disk space on scratch1 on frontera and it is not close to full.
* I'm able to go the execution folder and run job using sbatch. But, with tapis it fails.
* My ssh is setup and credentials are created.

**Comment by dvernon-tacc** [comment] 2023-06-28 21:56
This is a files issue.  I added one for it - https://github.com/tapis-project/tapis-files/issues/108
I will leave this open to track the problem since although the problem is in files, it appears as a jobs error.  Rich - you can do whatever you prefer about leaving it open or closing it.

**Comment by richcar58** [comment] 2023-08-01 14:35
Duplicate issue.

**Closed as completed by richcar58** 2023-08-01 14:35 UTC
