### ISSUE TITLE
job archive filter not honoring macros

### ISSUE THREAD

**Issue by JoshuaUrrutia** [tapis-project/tapis-jobs#86] opened 2024-05-23 18:05 UTC
When I use a macro to rename the log files, they are missed by the "archiveFilter", for example this combination:
```
"archiveFilter": {
		"excludes": [
			"tapisjob.sh",
			"${JobUUID}.out",
			"${JobUUID}.err",
			"tapisjob.env"
		],
		"includeLaunchFiles": false,
		"includes": []
	},
"logConfig": {
            "stderrFilename": "${JobUUID}.err",
            "stdoutFilename": "${JobUUID}.out"
},
```
The `tapisjob.env` and `tapisjob.sh` files are filtered from the archive location, but the .out/.err files are still being archived.

**Comment by richcar58** [comment] 2024-08-29 22:09
Duplicate of https://github.com/tapis-project/tapis-jobs/issues/100.

**Closed as completed by richcar58** 2024-08-29 22:09 UTC
